spring.application.name=order-service
server.port=8081

spring.data.mongodb.uri=mongodb+srv://ITE5315-Riya:Riya%402314@ite5315-riya.dxfg7.mongodb.net/orders?retryWrites=true&w=majority

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.instance-id=${spring.application.name}:${server.port}
