# order-service/src/main/resources/application.properties

server.port=8081
spring.application.name=order-service

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# MongoDB connection (make sure MongoDB is running locally)
spring.data.mongodb.uri=mongodb+srv://ITE5315-Riya:Riya%402314@ite5315-riya.dxfg7.mongodb.net/orderdb?retryWrites=true&w=majority

# Jackson config to keep date formats readable
spring.jackson.serialization.write-dates-as-timestamps=false

eureka.instance.instance-id=${spring.application.name}:${spring.cloud.client.ip-address:${spring.cloud.client.hostname}}:${server.port}

