server.port=8083
spring.application.name=market-service
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# MongoDB
spring.data.mongodb.uri=mongodb+srv://ITE5315-Riya:Riya%402314@ite5315-riya.dxfg7.mongodb.net/marketdb?retryWrites=true&w=majority
# Jackson Java time
spring.jackson.serialization.write-dates-as-timestamps=false
eureka.instance.instance-id=${spring.application.name}:${server.port}:${random.value}
